version: '3.8'

services:
  telegram-bot:
    image: python:3.9-slim
    container_name: telegram-bot
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env
    command: bash -c "pip install -r requirements.txt && python bot.py"
